import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/question_model.dart';

class QuizService {
  static final FirebaseFirestore _db = FirebaseFirestore.instance;
  static const String _collection = 'quiz_questions';

  // Fetch questions by language and level
  static Future<List<QuestionModel>> getQuestions({
    required String language,
    required String level,
  }) async {
    try {
      final snapshot = await _db
          .collection(_collection)
          .where('language', isEqualTo: language)
          .where('level', isEqualTo: level)
          .get();

      return snapshot.docs
          .map((doc) => QuestionModel.fromFirestore(doc.data(), doc.id))
          .toList();
    } catch (e) {
      return [];
    }
  }

  // Upload questions to Firestore (run once to seed data)
  static Future<void> uploadQuestions() async {
    final questions = _getAllQuestions();
    final batch = _db.batch();

    for (var q in questions) {
      final ref = _db.collection(_collection).doc();
      batch.set(ref, q.toMap());
    }
    await batch.commit();
  }

  static List<QuestionModel> _getAllQuestions() {
    return [
      // ─── PYTHON BEGINNER ───
      QuestionModel(id: '', language: 'Python', level: 'Beginner',
        question: 'How do you print "Hello" in Python?',
        options: ['print("Hello")', 'echo "Hello"', 'console.log("Hello")', 'printf("Hello")'],
        answer: 'print("Hello")'),
      QuestionModel(id: '', language: 'Python', level: 'Beginner',
        question: 'How do you create a variable in Python?',
        options: ['x = 5', 'var x = 5', 'int x = 5', 'let x = 5'],
        answer: 'x = 5'),
      QuestionModel(id: '', language: 'Python', level: 'Beginner',
        question: 'Which symbol is used for comments in Python?',
        options: ['#', '//', '/*', '--'],
        answer: '#'),
      QuestionModel(id: '', language: 'Python', level: 'Beginner',
        question: 'What is the output of print(2 + 3)?',
        options: ['5', '23', 'Error', 'None'],
        answer: '5'),
      QuestionModel(id: '', language: 'Python', level: 'Beginner',
        question: 'How do you take input from user in Python?',
        options: ['input()', 'scan()', 'read()', 'get()'],
        answer: 'input()'),

      // ─── PYTHON INTERMEDIATE ───
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'What does len([1,2,3]) return?',
        options: ['3', '2', '1', 'Error'],
        answer: '3'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'Which keyword defines a function in Python?',
        options: ['def', 'func', 'function', 'define'],
        answer: 'def'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'What is a list comprehension?',
        options: ['[x for x in range(5)]', '{x for x in range(5)}', '(x for x in range(5))', 'None'],
        answer: '[x for x in range(5)]'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'What does range(1, 5) produce?',
        options: ['1,2,3,4', '1,2,3,4,5', '0,1,2,3,4', '2,3,4,5'],
        answer: '1,2,3,4'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'How do you open a file in Python?',
        options: ['open("file.txt")', 'file.open("file.txt")', 'read("file.txt")', 'load("file.txt")'],
        answer: 'open("file.txt")')
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'What is a dictionary in Python?',
        options: ['{"key": "value"}', '["key", "value"]', '("key", "value")', 'None'],
        answer: '{"key": "value"}'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'How do you handle exceptions?',
        options: ['try-except', 'catch-throw', 'handle-error', 'trap-fix'],
        answer: 'try-except'),
      QuestionModel(id: '', language: 'Python', level: 'Intermediate',
        question: 'What is enumerate() used for?',
        options: ['Get index and value', 'Count items', 'Sort items', 'Filter items'],
        answer: 'Get index and value'),,

      // ─── PYTHON ADVANCED ───
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is a decorator in Python?',
        options: ['A function that wraps another function', 'A class', 'A variable', 'A loop'],
        answer: 'A function that wraps another function'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What does *args do in a function?',
        options: ['Accepts multiple positional arguments', 'Accepts keyword arguments', 'Returns multiple values', 'None'],
        answer: 'Accepts multiple positional arguments'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is a generator in Python?',
        options: ['A function using yield', 'A class', 'A list', 'A decorator'],
        answer: 'A function using yield'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is GIL in Python?',
        options: ['Global Interpreter Lock', 'General Input Loop', 'Global Input List', 'None'],
        answer: 'Global Interpreter Lock'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What does __init__ do in a class?',
        options: ['Initializes object', 'Deletes object', 'Copies object', 'Prints object'],
        answer: 'Initializes object'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is metaclass in Python?',
        options: ['A class of a class', 'A function', 'A variable', 'A module'],
        answer: 'A class of a class'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What does async/await do?',
        options: ['Handles asynchronous operations', 'Creates threads', 'Imports modules', 'None'],
        answer: 'Handles asynchronous operations'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is context manager?',
        options: ['Manages resource allocation', 'A function', 'A class method', 'None'],
        answer: 'Manages resource allocation'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is the difference between __str__ and __repr__?',
        options: ['__str__ for users, __repr__ for developers', '__repr__ for users, __str__ for developers', 'Both are same', 'None'],
        answer: '__str__ for users, __repr__ for developers'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is monkey patching?',
        options: ['Modifying classes at runtime', 'Error handling', 'Memory management', 'File operations'],
        answer: 'Modifying classes at runtime'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What does yield keyword do?',
        options: ['Creates generator function', 'Returns value', 'Breaks loop', 'Imports module'],
        answer: 'Creates generator function'),
      QuestionModel(id: '', language: 'Python', level: 'Advanced',
        question: 'What is list comprehension with condition?',
        options: ['[x for x in list if condition]', '[x if condition for x in list]', '[x for x if condition in list]', 'None'],
        answer: '[x for x in list if condition]'),

      // ─── JAVA BEGINNER ───
      QuestionModel(id: '', language: 'Java', level: 'Beginner',
        question: 'How do you print in Java?',
        options: ['System.out.println()', 'print()', 'console.log()', 'echo()'],
        answer: 'System.out.println()'),
      QuestionModel(id: '', language: 'Java', level: 'Beginner',
        question: 'Which data type stores whole numbers in Java?',
        options: ['int', 'float', 'String', 'boolean'],
        answer: 'int'),
      QuestionModel(id: '', language: 'Java', level: 'Beginner',
        question: 'How do you declare a String in Java?',
        options: ['String name = "John"', 'str name = "John"', 'name = "John"', 'var name = "John"'],
        answer: 'String name = "John"'),
      QuestionModel(id: '', language: 'Java', level: 'Beginner',
        question: 'What ends every Java statement?',
        options: [';', '.', ',', ':'],
        answer: ';'),
      QuestionModel(id: '', language: 'Java', level: 'Beginner',
        question: 'Which keyword creates a class in Java?',
        options: ['class', 'Class', 'object', 'new'],
        answer: 'class'),

      // ─── JAVA INTERMEDIATE ───
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What is a constructor in Java?',
        options: ['A special method to initialize objects', 'A variable', 'A loop', 'A class'],
        answer: 'A special method to initialize objects'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What is inheritance in Java?',
        options: ['A class acquiring properties of another', 'A loop', 'A variable', 'A method'],
        answer: 'A class acquiring properties of another'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'Which keyword is used for inheritance?',
        options: ['extends', 'implements', 'inherits', 'super'],
        answer: 'extends'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What is an interface in Java?',
        options: ['A blueprint with abstract methods', 'A class', 'A variable', 'A loop'],
        answer: 'A blueprint with abstract methods'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What does ArrayList store?',
        options: ['Dynamic list of objects', 'Fixed array', 'Only integers', 'Only strings'],
        answer: 'Dynamic list of objects'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What is method overloading?',
        options: ['Same method name, different parameters', 'Different method names', 'Only one method', 'None'],
        answer: 'Same method name, different parameters'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What is encapsulation?',
        options: ['Data hiding using private/public', 'Inheritance', 'Polymorphism', 'Abstraction'],
        answer: 'Data hiding using private/public'),
      QuestionModel(id: '', language: 'Java', level: 'Intermediate',
        question: 'What does static keyword mean?',
        options: ['Belongs to class, not instance', 'Dynamic allocation', 'Private access', 'None'],
        answer: 'Belongs to class, not instance'),,

      // ─── JAVA ADVANCED ───
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is multithreading in Java?',
        options: ['Running multiple threads simultaneously', 'A loop', 'A class', 'A variable'],
        answer: 'Running multiple threads simultaneously'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is the purpose of synchronized keyword?',
        options: ['Prevent thread interference', 'Speed up code', 'Create threads', 'Delete threads'],
        answer: 'Prevent thread interference'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is a lambda expression in Java?',
        options: ['A short anonymous function', 'A class', 'A variable', 'A loop'],
        answer: 'A short anonymous function'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What does JVM stand for?',
        options: ['Java Virtual Machine', 'Java Variable Method', 'Java Visual Mode', 'None'],
        answer: 'Java Virtual Machine'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is garbage collection in Java?',
        options: ['Automatic memory management', 'Deleting files', 'Clearing screen', 'None'],
        answer: 'Automatic memory management'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is the difference between ArrayList and LinkedList?',
        options: ['ArrayList uses array, LinkedList uses nodes', 'Both are same', 'LinkedList is faster', 'ArrayList is deprecated'],
        answer: 'ArrayList uses array, LinkedList uses nodes'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is method overriding?',
        options: ['Redefining parent class method', 'Creating new method', 'Deleting method', 'Copying method'],
        answer: 'Redefining parent class method'),
      QuestionModel(id: '', language: 'Java', level: 'Advanced',
        question: 'What is the final keyword used for?',
        options: ['Prevent inheritance/modification', 'Speed up execution', 'Memory allocation', 'Error handling'],
        answer: 'Prevent inheritance/modification'),,

      // ─── C BEGINNER ───
      QuestionModel(id: '', language: 'C', level: 'Beginner',
        question: 'How do you print in C?',
        options: ['printf()', 'print()', 'cout()', 'echo()'],
        answer: 'printf()'),
      QuestionModel(id: '', language: 'C', level: 'Beginner',
        question: 'Which header file is needed for printf?',
        options: ['#include <stdio.h>', '#include <math.h>', '#include <string.h>', '#include <stdlib.h>'],
        answer: '#include <stdio.h>'),
      QuestionModel(id: '', language: 'C', level: 'Beginner',
        question: 'How do you declare an integer in C?',
        options: ['int x = 5;', 'integer x = 5;', 'var x = 5;', 'x = 5;'],
        answer: 'int x = 5;'),
      QuestionModel(id: '', language: 'C', level: 'Beginner',
        question: 'What is %d used for in printf?',
        options: ['Print integer', 'Print float', 'Print string', 'Print char'],
        answer: 'Print integer'),
      QuestionModel(id: '', language: 'C', level: 'Beginner',
        question: 'How do you take input in C?',
        options: ['scanf()', 'input()', 'read()', 'get()'],
        answer: 'scanf()'),

      // ─── C INTERMEDIATE ───
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What is a pointer in C?',
        options: ['A variable storing memory address', 'A function', 'A loop', 'An array'],
        answer: 'A variable storing memory address'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What does malloc() do?',
        options: ['Allocates memory dynamically', 'Frees memory', 'Prints output', 'Reads input'],
        answer: 'Allocates memory dynamically'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What is a struct in C?',
        options: ['A user-defined data type', 'A loop', 'A function', 'A pointer'],
        answer: 'A user-defined data type'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What does & operator do in C?',
        options: ['Gets address of variable', 'Adds two numbers', 'Logical AND', 'Bitwise OR'],
        answer: 'Gets address of variable'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What is recursion?',
        options: ['A function calling itself', 'A loop', 'A pointer', 'A struct'],
        answer: 'A function calling itself'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What is the difference between malloc and calloc?',
        options: ['calloc initializes to zero', 'malloc is faster', 'No difference', 'calloc is deprecated'],
        answer: 'calloc initializes to zero'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What is a union in C?',
        options: ['Shares memory among members', 'Separate memory for each member', 'A type of struct', 'A pointer type'],
        answer: 'Shares memory among members'),
      QuestionModel(id: '', language: 'C', level: 'Intermediate',
        question: 'What does free() function do?',
        options: ['Deallocates memory', 'Allocates memory', 'Copies memory', 'Clears memory'],
        answer: 'Deallocates memory'),,

      // ─── C ADVANCED ───
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is a memory leak?',
        options: ['Allocated memory not freed', 'A bug in loop', 'A pointer error', 'None'],
        answer: 'Allocated memory not freed'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What does free() do in C?',
        options: ['Releases allocated memory', 'Allocates memory', 'Prints output', 'None'],
        answer: 'Releases allocated memory'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is a function pointer?',
        options: ['A pointer pointing to a function', 'A function returning pointer', 'A struct', 'None'],
        answer: 'A pointer pointing to a function'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is the difference between stack and heap?',
        options: ['Stack is static, heap is dynamic', 'Both are same', 'Heap is faster', 'None'],
        answer: 'Stack is static, heap is dynamic'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What does volatile keyword do in C?',
        options: ['Prevents compiler optimization', 'Speeds up code', 'Allocates memory', 'None'],
        answer: 'Prevents compiler optimization'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is dangling pointer?',
        options: ['Pointer to deallocated memory', 'Null pointer', 'Valid pointer', 'Array pointer'],
        answer: 'Pointer to deallocated memory'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is the purpose of const keyword?',
        options: ['Make variable read-only', 'Speed up execution', 'Allocate memory', 'Free memory'],
        answer: 'Make variable read-only'),
      QuestionModel(id: '', language: 'C', level: 'Advanced',
        question: 'What is segmentation fault?',
        options: ['Accessing invalid memory', 'Syntax error', 'Logic error', 'Compilation error'],
        answer: 'Accessing invalid memory'),,

      // ─── HTML BEGINNER ───
      QuestionModel(id: '', language: 'HTML', level: 'Beginner',
        question: 'What does HTML stand for?',
        options: ['HyperText Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'None'],
        answer: 'HyperText Markup Language'),
      QuestionModel(id: '', language: 'HTML', level: 'Beginner',
        question: 'Which tag creates a heading in HTML?',
        options: ['<h1>', '<head>', '<header>', '<title>'],
        answer: '<h1>'),
      QuestionModel(id: '', language: 'HTML', level: 'Beginner',
        question: 'Which tag creates a paragraph?',
        options: ['<p>', '<para>', '<text>', '<div>'],
        answer: '<p>'),
      QuestionModel(id: '', language: 'HTML', level: 'Beginner',
        question: 'How do you create a link in HTML?',
        options: ['<a href="url">text</a>', '<link>text</link>', '<url>text</url>', '<href>text</href>'],
        answer: '<a href="url">text</a>'),
      QuestionModel(id: '', language: 'HTML', level: 'Beginner',
        question: 'Which tag adds an image?',
        options: ['<img src="url">', '<image src="url">', '<pic src="url">', '<photo src="url">'],
        answer: '<img src="url">'),

      // ─── HTML INTERMEDIATE ───
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'What does CSS stand for?',
        options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style Sheets', 'None'],
        answer: 'Cascading Style Sheets'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'How do you change text color in CSS?',
        options: ['color: red;', 'text-color: red;', 'font-color: red;', 'style: red;'],
        answer: 'color: red;'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'Which CSS property controls font size?',
        options: ['font-size', 'text-size', 'font', 'size'],
        answer: 'font-size'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'What is the CSS box model?',
        options: ['Content, padding, border, margin', 'Width and height only', 'Color and font', 'None'],
        answer: 'Content, padding, border, margin'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'How do you create a CSS class selector?',
        options: ['.classname', '#classname', 'classname', '*classname'],
        answer: '.classname'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'What is Flexbox used for?',
        options: ['Layout and alignment', 'Text styling', 'Image effects', 'Animations'],
        answer: 'Layout and alignment'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'How do you make text bold in CSS?',
        options: ['font-weight: bold;', 'text-bold: true;', 'bold: yes;', 'weight: bold;'],
        answer: 'font-weight: bold;'),
      QuestionModel(id: '', language: 'HTML', level: 'Intermediate',
        question: 'What does display: none; do?',
        options: ['Hides element completely', 'Makes transparent', 'Changes color', 'Moves element'],
        answer: 'Hides element completely'),,

      // ─── HTML ADVANCED ───
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is Flexbox in CSS?',
        options: ['A layout model for arranging elements', 'A font style', 'A color system', 'None'],
        answer: 'A layout model for arranging elements'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is CSS Grid?',
        options: ['A 2D layout system', 'A 1D layout system', 'A font system', 'None'],
        answer: 'A 2D layout system'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is a media query in CSS?',
        options: ['Applies styles based on screen size', 'Loads images', 'Plays videos', 'None'],
        answer: 'Applies styles based on screen size'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What does z-index do in CSS?',
        options: ['Controls stacking order of elements', 'Sets font size', 'Changes color', 'None'],
        answer: 'Controls stacking order of elements'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is the difference between id and class in CSS?',
        options: ['id is unique, class can be reused', 'Both are same', 'class is unique', 'None'],
        answer: 'id is unique, class can be reused'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is CSS specificity?',
        options: ['Priority of CSS rules', 'CSS file size', 'Loading speed', 'Color depth'],
        answer: 'Priority of CSS rules'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What is a CSS pseudo-class?',
        options: ['Styles based on element state', 'Fake CSS class', 'JavaScript class', 'HTML attribute'],
        answer: 'Styles based on element state'),
      QuestionModel(id: '', language: 'HTML', level: 'Advanced',
        question: 'What does position: absolute do?',
        options: ['Positions relative to nearest positioned parent', 'Positions relative to viewport', 'Removes from document flow', 'Makes element sticky'],
        answer: 'Positions relative to nearest positioned parent'),,
    ];
  }
}
