// practice_data.dart — Coding problems per language per level per topic

class ProblemData {
  final String title;
  final String problem;
  final String inputFormat;
  final String outputFormat;
  final String sampleInput;
  final String sampleOutput;
  final String explanation;
  final String hint;
  final String answer;

  const ProblemData({
    required this.title,
    required this.problem,
    required this.inputFormat,
    required this.outputFormat,
    required this.sampleInput,
    required this.sampleOutput,
    required this.explanation,
    required this.hint,
    required this.answer,
  });
}

// ══════════════════════════════════════════════════════════════════
// PYTHON
// ══════════════════════════════════════════════════════════════════
const Map<String, Map<String, List<ProblemData>>> practiceData = {

  'Python': {

    // ── BEGINNER ──────────────────────────────────────────────────
    'Beginner Level': [
      ProblemData(
        title: 'Hello World',
        problem: 'Write a Python program that prints "Hello, World!" to the screen.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Hello, World!',
        sampleInput: '(none)',
        sampleOutput: 'Hello, World!',
        explanation: 'Use the print() function to display text on screen.',
        hint: 'Use: print("Hello, World!")',
        answer: 'print("Hello, World!")',
      ),
      ProblemData(
        title: 'Variable Assignment',
        problem: 'Create a variable called name with value "Alice" and age with value 20. Print both.',
        inputFormat: 'No input required.',
        outputFormat: 'Print name then age on separate lines.',
        sampleInput: '(none)',
        sampleOutput: 'Alice\n20',
        explanation: 'Assign values using = and print each variable.',
        hint: 'name = "Alice"\nage = 20',
        answer: 'name = "Alice"\nage = 20\nprint(name)\nprint(age)',
      ),
      ProblemData(
        title: 'Sum of Two Numbers',
        problem: 'Take two integer inputs from the user and print their sum.',
        inputFormat: 'Two integers on separate lines.',
        outputFormat: 'Print the sum.',
        sampleInput: '5\n3',
        sampleOutput: '8',
        explanation: 'Read two inputs, convert to int, add and print.',
        hint: 'Use: int(input())',
        answer: 'a = int(input())\nb = int(input())\nprint(a + b)',
      ),
      ProblemData(
        title: 'Even or Odd',
        problem: 'Take an integer input and print "Even" if it is even, otherwise print "Odd".',
        inputFormat: 'Single integer.',
        outputFormat: 'Print Even or Odd.',
        sampleInput: '4',
        sampleOutput: 'Even',
        explanation: 'Use % 2 to check remainder. If 0, it\'s even.',
        hint: 'Use: if n % 2 == 0:',
        answer: 'n = int(input())\nif n % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")',
      ),
      ProblemData(
        title: 'Print 1 to 5',
        problem: 'Use a for loop to print numbers 1 to 5, each on a new line.',
        inputFormat: 'No input required.',
        outputFormat: 'Print 1 through 5.',
        sampleInput: '(none)',
        sampleOutput: '1\n2\n3\n4\n5',
        explanation: 'range(1, 6) gives numbers 1 to 5.',
        hint: 'Use: for i in range(1, 6):',
        answer: 'for i in range(1, 6):\n    print(i)',
      ),
      ProblemData(
        title: 'Multiplication Table',
        problem: 'Take an integer n as input. Print its multiplication table from 1 to 5.',
        inputFormat: 'Single integer n.',
        outputFormat: 'Print n x 1 = result for each line.',
        sampleInput: '3',
        sampleOutput: '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15',
        explanation: 'Loop from 1 to 5 and print n * i.',
        hint: 'Use: for i in range(1, 6): print(n, "x", i, "=", n*i)',
        answer: 'n = int(input())\nfor i in range(1, 6):\n    print(n, "x", i, "=", n * i)',
      ),
      ProblemData(
        title: 'List Sum',
        problem: 'Create a list of 5 numbers: [10, 20, 30, 40, 50]. Print the sum.',
        inputFormat: 'No input required.',
        outputFormat: 'Print the sum.',
        sampleInput: '(none)',
        sampleOutput: '150',
        explanation: 'Use the built-in sum() function on the list.',
        hint: 'Use: sum(list)',
        answer: 'nums = [10, 20, 30, 40, 50]\nprint(sum(nums))',
      ),
      ProblemData(
        title: 'Greet Function',
        problem: 'Define a function greet(name) that prints "Hello, <name>!". Call it with "Bob".',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Hello, Bob!',
        sampleInput: '(none)',
        sampleOutput: 'Hello, Bob!',
        explanation: 'Define with def and call the function.',
        hint: 'def greet(name):\n    print("Hello,", name + "!")',
        answer: 'def greet(name):\n    print("Hello, " + name + "!")\ngreet("Bob")',
      ),
    ],

    // ── INTERMEDIATE ──────────────────────────────────────────────
    'Intermediate Level': [
      ProblemData(
        title: 'Reverse a String',
        problem: 'Take a string input and print it in reverse.',
        inputFormat: 'A single string.',
        outputFormat: 'Print the reversed string.',
        sampleInput: 'hello',
        sampleOutput: 'olleh',
        explanation: 'Use Python slicing: s[::-1] reverses a string.',
        hint: 'Use: s[::-1]',
        answer: 's = input()\nprint(s[::-1])',
      ),
      ProblemData(
        title: 'Count Vowels',
        problem: 'Take a string input and count the number of vowels (a, e, i, o, u).',
        inputFormat: 'A single string (lowercase).',
        outputFormat: 'Print the count of vowels.',
        sampleInput: 'hello',
        sampleOutput: '2',
        explanation: 'Iterate through the string, check if each char is a vowel.',
        hint: 'Use: for c in s: if c in "aeiou":',
        answer: 's = input()\ncount = sum(1 for c in s if c in "aeiou")\nprint(count)',
      ),
      ProblemData(
        title: 'Factorial with Function',
        problem: 'Write a function factorial(n) that returns n! using recursion.',
        inputFormat: 'Single integer n (0 <= n <= 10).',
        outputFormat: 'Print factorial of n.',
        sampleInput: '5',
        sampleOutput: '120',
        explanation: 'Base case: factorial(0) = 1. Recursive: n * factorial(n-1).',
        hint: 'def factorial(n):\n    if n == 0: return 1\n    return n * factorial(n-1)',
        answer: 'def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\nn = int(input())\nprint(factorial(n))',
      ),
      ProblemData(
        title: 'Find Maximum in List',
        problem: 'Given a list [3, 1, 7, 2, 9, 4], find and print the maximum value without using max().',
        inputFormat: 'No input required.',
        outputFormat: 'Print the maximum value.',
        sampleInput: '(none)',
        sampleOutput: '9',
        explanation: 'Iterate through the list, track the largest value seen.',
        hint: 'Start with largest = list[0], loop and compare.',
        answer: 'nums = [3, 1, 7, 2, 9, 4]\nlargest = nums[0]\nfor n in nums:\n    if n > largest:\n        largest = n\nprint(largest)',
      ),
      ProblemData(
        title: 'Dictionary Word Count',
        problem: 'Count the frequency of each word in the string: "the cat sat on the mat".',
        inputFormat: 'No input required.',
        outputFormat: 'Print each word and its count.',
        sampleInput: '(none)',
        sampleOutput: 'the: 2\ncat: 1\nsat: 1\non: 1\nmat: 1',
        explanation: 'Split the string, use a dict to count each word.',
        hint: 'Use: words.split() and a dict',
        answer: 'words = "the cat sat on the mat"\ncounts = {}\nfor w in words.split():\n    counts[w] = counts.get(w, 0) + 1\nfor k, v in counts.items():\n    print(f"{k}: {v}")',
      ),
      ProblemData(
        title: 'Exception Handling',
        problem: 'Write a program that reads an integer. If input is not a number, print "Invalid input".',
        inputFormat: 'Any input from user.',
        outputFormat: 'Print the number or "Invalid input".',
        sampleInput: 'abc',
        sampleOutput: 'Invalid input',
        explanation: 'Wrap int(input()) in try-except ValueError.',
        hint: 'try:\n    n = int(input())\nexcept ValueError:\n    print("Invalid input")',
        answer: 'try:\n    n = int(input())\n    print(n)\nexcept ValueError:\n    print("Invalid input")',
      ),
      ProblemData(
        title: 'Class: Rectangle',
        problem: 'Create a class Rectangle with width and height. Add method area() that returns width * height.',
        inputFormat: 'No input required.',
        outputFormat: 'Print area of rectangle with width=5, height=3.',
        sampleInput: '(none)',
        sampleOutput: '15',
        explanation: 'Define __init__ with self.width, self.height. Define area().',
        hint: 'class Rectangle:\n    def __init__(self, w, h):\n        self.width = w',
        answer: 'class Rectangle:\n    def __init__(self, w, h):\n        self.width = w\n        self.height = h\n    def area(self):\n        return self.width * self.height\nr = Rectangle(5, 3)\nprint(r.area())',
      ),
      ProblemData(
        title: 'Bubble Sort',
        problem: 'Implement bubble sort to sort the list [64, 25, 12, 22, 11] in ascending order.',
        inputFormat: 'No input required.',
        outputFormat: 'Print the sorted list.',
        sampleInput: '(none)',
        sampleOutput: '[11, 12, 22, 25, 64]',
        explanation: 'Compare adjacent elements and swap if out of order. Repeat.',
        hint: 'Use nested loops: outer for passes, inner for comparisons.',
        answer: 'arr = [64, 25, 12, 22, 11]\nn = len(arr)\nfor i in range(n):\n    for j in range(0, n-i-1):\n        if arr[j] > arr[j+1]:\n            arr[j], arr[j+1] = arr[j+1], arr[j]\nprint(arr)',
      ),
    ],

    // ── ADVANCED ──────────────────────────────────────────────────
    'Advanced Level': [
      ProblemData(
        title: 'Binary Search',
        problem: 'Implement binary search. Given sorted list [1,3,5,7,9,11,13] and target 7, return its index.',
        inputFormat: 'No input required.',
        outputFormat: 'Print the index of the target.',
        sampleInput: '(none)',
        sampleOutput: '3',
        explanation: 'Binary search halves the search space each time O(log n).',
        hint: 'Use left, right pointers. mid = (left + right) // 2',
        answer: 'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\narr = [1, 3, 5, 7, 9, 11, 13]\nprint(binary_search(arr, 7))',
      ),
      ProblemData(
        title: 'Fibonacci with Memoization',
        problem: 'Write a function fib(n) using memoization (dict cache) to return the nth Fibonacci number.',
        inputFormat: 'Single integer n.',
        outputFormat: 'Print fib(n).',
        sampleInput: '10',
        sampleOutput: '55',
        explanation: 'Store previously computed values in a dict to avoid redundant calls.',
        hint: 'Use a dict: memo = {}. Check if n in memo before computing.',
        answer: 'memo = {}\ndef fib(n):\n    if n <= 1:\n        return n\n    if n in memo:\n        return memo[n]\n    memo[n] = fib(n-1) + fib(n-2)\n    return memo[n]\nn = int(input())\nprint(fib(n))',
      ),
      ProblemData(
        title: 'Stack Implementation',
        problem: 'Implement a Stack class with push(x), pop(), peek(), and is_empty() methods.',
        inputFormat: 'No input required.',
        outputFormat: 'Push 1,2,3. Print peek. Pop and print. Print peek.',
        sampleInput: '(none)',
        sampleOutput: '3\n3\n2',
        explanation: 'Use a list internally. Push appends, pop removes last.',
        hint: 'class Stack:\n    def __init__(self):\n        self.data = []',
        answer: 'class Stack:\n    def __init__(self):\n        self.data = []\n    def push(self, x):\n        self.data.append(x)\n    def pop(self):\n        return self.data.pop()\n    def peek(self):\n        return self.data[-1]\n    def is_empty(self):\n        return len(self.data) == 0\ns = Stack()\ns.push(1)\ns.push(2)\ns.push(3)\nprint(s.peek())\nprint(s.pop())\nprint(s.peek())',
      ),
      ProblemData(
        title: 'Decorator: Timer',
        problem: 'Write a decorator @timer that prints the execution time of any function.',
        inputFormat: 'No input required.',
        outputFormat: 'Print "Executed in X seconds" (any float value is acceptable).',
        sampleInput: '(none)',
        sampleOutput: 'Executed in 0.0001 seconds',
        explanation: 'Record time before and after function call using time module.',
        hint: 'import time\ndef timer(func):\n    def wrapper(*args):\n        start = time.time()',
        answer: 'import time\ndef timer(func):\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        end = time.time()\n        print(f"Executed in {end - start:.4f} seconds")\n        return result\n    return wrapper\n@timer\ndef sample():\n    total = sum(range(1000))\nsample()',
      ),
      ProblemData(
        title: 'List Comprehension Filter',
        problem: 'Given numbers 1-20, use list comprehension to get numbers divisible by both 3 and 5.',
        inputFormat: 'No input required.',
        outputFormat: 'Print the filtered list.',
        sampleInput: '(none)',
        sampleOutput: '[15]',
        explanation: 'Use [x for x in range(1,21) if x%3==0 and x%5==0].',
        hint: 'Use: [x for x in range(1, 21) if ...]',
        answer: 'result = [x for x in range(1, 21) if x % 3 == 0 and x % 5 == 0]\nprint(result)',
      ),
      ProblemData(
        title: 'Linked List',
        problem: 'Implement a singly linked list with append(data) and print_list() methods.',
        inputFormat: 'No input required.',
        outputFormat: 'Append 1, 2, 3 then print: 1 -> 2 -> 3 -> None',
        sampleInput: '(none)',
        sampleOutput: '1 -> 2 -> 3 -> None',
        explanation: 'Node class holds data and next pointer. LinkedList manages head.',
        hint: 'class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None',
        answer: 'class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\nclass LinkedList:\n    def __init__(self):\n        self.head = None\n    def append(self, data):\n        new = Node(data)\n        if not self.head:\n            self.head = new\n            return\n        cur = self.head\n        while cur.next:\n            cur = cur.next\n        cur.next = new\n    def print_list(self):\n        cur = self.head\n        result = []\n        while cur:\n            result.append(str(cur.data))\n            cur = cur.next\n        print(" -> ".join(result) + " -> None")\nll = LinkedList()\nll.append(1)\nll.append(2)\nll.append(3)\nll.print_list()',
      ),
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // JAVA
  // ══════════════════════════════════════════════════════════════════
  'Java': {

    'Beginner Level': [
      ProblemData(
        title: 'Hello World',
        problem: 'Write a Java program to print "Hello, World!".',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Hello, World!',
        sampleInput: '(none)',
        sampleOutput: 'Hello, World!',
        explanation: 'Use System.out.println() to print to console.',
        hint: 'System.out.println("Hello, World!");',
        answer: 'System.out.println("Hello, World!");',
      ),
      ProblemData(
        title: 'Declare Variables',
        problem: 'Declare an int age = 20 and String name = "Alice". Print both.',
        inputFormat: 'No input required.',
        outputFormat: 'Print name then age.',
        sampleInput: '(none)',
        sampleOutput: 'Alice\n20',
        explanation: 'Declare variables with their types and use println.',
        hint: 'String name = "Alice";\nint age = 20;',
        answer: 'String name = "Alice";\nint age = 20;\nSystem.out.println(name);\nSystem.out.println(age);',
      ),
      ProblemData(
        title: 'Sum of Two Numbers',
        problem: 'Read two integers from Scanner and print their sum.',
        inputFormat: 'Two integers on separate lines.',
        outputFormat: 'Print the sum.',
        sampleInput: '5\n3',
        sampleOutput: '8',
        explanation: 'Use Scanner to read ints and add them.',
        hint: 'Scanner sc = new Scanner(System.in);\nint a = sc.nextInt();',
        answer: 'Scanner sc = new Scanner(System.in);\nint a = sc.nextInt();\nint b = sc.nextInt();\nSystem.out.println(a + b);',
      ),
      ProblemData(
        title: 'Even or Odd',
        problem: 'Read an integer and print "Even" or "Odd".',
        inputFormat: 'Single integer.',
        outputFormat: 'Print Even or Odd.',
        sampleInput: '7',
        sampleOutput: 'Odd',
        explanation: 'Use % 2 to check remainder.',
        hint: 'if (n % 2 == 0) System.out.println("Even");',
        answer: 'Scanner sc = new Scanner(System.in);\nint n = sc.nextInt();\nif (n % 2 == 0) {\n    System.out.println("Even");\n} else {\n    System.out.println("Odd");\n}',
      ),
      ProblemData(
        title: 'Print 1 to 5',
        problem: 'Use a for loop to print numbers 1 to 5.',
        inputFormat: 'No input required.',
        outputFormat: 'Print 1 through 5.',
        sampleInput: '(none)',
        sampleOutput: '1\n2\n3\n4\n5',
        explanation: 'for loop from 1 to 5 inclusive.',
        hint: 'for (int i = 1; i <= 5; i++)',
        answer: 'for (int i = 1; i <= 5; i++) {\n    System.out.println(i);\n}',
      ),
      ProblemData(
        title: 'Array Sum',
        problem: 'Declare an int array {10, 20, 30, 40, 50} and print the sum.',
        inputFormat: 'No input required.',
        outputFormat: 'Print the sum.',
        sampleInput: '(none)',
        sampleOutput: '150',
        explanation: 'Loop through array and accumulate sum.',
        hint: 'int[] arr = {10,20,30,40,50};\nint sum = 0;',
        answer: 'int[] arr = {10, 20, 30, 40, 50};\nint sum = 0;\nfor (int x : arr) {\n    sum += x;\n}\nSystem.out.println(sum);',
      ),
      ProblemData(
        title: 'Static Method Add',
        problem: 'Write a static method add(int a, int b) that returns a + b. Call it with 4 and 6.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 10',
        sampleInput: '(none)',
        sampleOutput: '10',
        explanation: 'Declare static int method, return sum, call from main.',
        hint: 'static int add(int a, int b) { return a + b; }',
        answer: 'static int add(int a, int b) {\n    return a + b;\n}\nSystem.out.println(add(4, 6));',
      ),
      ProblemData(
        title: 'Factorial Loop',
        problem: 'Read integer n from Scanner and print n! using a for loop.',
        inputFormat: 'Single integer n (1 <= n <= 10).',
        outputFormat: 'Print n factorial.',
        sampleInput: '5',
        sampleOutput: '120',
        explanation: 'Multiply 1 through n together.',
        hint: 'int fact = 1;\nfor (int i = 1; i <= n; i++) fact *= i;',
        answer: 'Scanner sc = new Scanner(System.in);\nint n = sc.nextInt();\nint fact = 1;\nfor (int i = 1; i <= n; i++) {\n    fact *= i;\n}\nSystem.out.println(fact);',
      ),
    ],

    'Intermediate Level': [
      ProblemData(
        title: 'Class: Rectangle',
        problem: 'Create a Rectangle class with width, height fields and area() method. Print area for 5x3.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 15',
        sampleInput: '(none)',
        sampleOutput: '15',
        explanation: 'Encapsulate fields, define constructor and area method.',
        hint: 'class Rectangle {\n    int width, height;\n    int area() { return width * height; }\n}',
        answer: 'class Rectangle {\n    int width, height;\n    Rectangle(int w, int h) {\n        this.width = w;\n        this.height = h;\n    }\n    int area() {\n        return width * height;\n    }\n}\nRectangle r = new Rectangle(5, 3);\nSystem.out.println(r.area());',
      ),
      ProblemData(
        title: 'Inheritance: Animal',
        problem: 'Create Animal class with sound() method. Dog extends Animal and overrides sound() to print "Woof".',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Woof',
        sampleInput: '(none)',
        sampleOutput: 'Woof',
        explanation: 'Use extends keyword and @Override annotation.',
        hint: 'class Dog extends Animal {\n    @Override\n    void sound() { System.out.println("Woof"); }\n}',
        answer: 'class Animal {\n    void sound() {\n        System.out.println("Some sound");\n    }\n}\nclass Dog extends Animal {\n    @Override\n    void sound() {\n        System.out.println("Woof");\n    }\n}\nnew Dog().sound();',
      ),
      ProblemData(
        title: 'ArrayList Operations',
        problem: 'Create ArrayList of Strings. Add "Java", "Python", "C". Remove "Python". Print the list.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: [Java, C]',
        sampleInput: '(none)',
        sampleOutput: '[Java, C]',
        explanation: 'Use ArrayList add() and remove() methods.',
        hint: 'ArrayList<String> list = new ArrayList<>();\nlist.add("Java");',
        answer: 'ArrayList<String> list = new ArrayList<>();\nlist.add("Java");\nlist.add("Python");\nlist.add("C");\nlist.remove("Python");\nSystem.out.println(list);',
      ),
      ProblemData(
        title: 'Exception Handling',
        problem: 'Read an integer from Scanner. Use try-catch to handle InputMismatchException and print "Invalid".',
        inputFormat: 'Any input.',
        outputFormat: 'Print integer or "Invalid".',
        sampleInput: 'abc',
        sampleOutput: 'Invalid',
        explanation: 'Wrap scanner.nextInt() in try-catch InputMismatchException.',
        hint: 'try { int n = sc.nextInt(); }\ncatch (InputMismatchException e) { System.out.println("Invalid"); }',
        answer: 'try {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    System.out.println(n);\n} catch (Exception e) {\n    System.out.println("Invalid");\n}',
      ),
      ProblemData(
        title: 'Bubble Sort',
        problem: 'Sort array {64, 25, 12, 22, 11} using bubble sort. Print sorted array.',
        inputFormat: 'No input required.',
        outputFormat: 'Print sorted array.',
        sampleInput: '(none)',
        sampleOutput: '11 12 22 25 64',
        explanation: 'Nested loops: compare adjacent elements and swap.',
        hint: 'for (int i=0; i<n-1; i++)\n  for (int j=0; j<n-i-1; j++)',
        answer: 'int[] arr = {64, 25, 12, 22, 11};\nint n = arr.length;\nfor (int i = 0; i < n-1; i++) {\n    for (int j = 0; j < n-i-1; j++) {\n        if (arr[j] > arr[j+1]) {\n            int tmp = arr[j];\n            arr[j] = arr[j+1];\n            arr[j+1] = tmp;\n        }\n    }\n}\nfor (int x : arr) System.out.print(x + " ");',
      ),
      ProblemData(
        title: 'Recursive Factorial',
        problem: 'Write recursive method factorial(int n). Print factorial of 6.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 720',
        sampleInput: '(none)',
        sampleOutput: '720',
        explanation: 'Base: n==0 return 1. Recursive: n * factorial(n-1).',
        hint: 'static int factorial(int n) {\n    if (n == 0) return 1;\n    return n * factorial(n-1);\n}',
        answer: 'static int factorial(int n) {\n    if (n == 0) return 1;\n    return n * factorial(n - 1);\n}\nSystem.out.println(factorial(6));',
      ),
      ProblemData(
        title: 'String Reverse',
        problem: 'Read a string and print it reversed using StringBuilder.',
        inputFormat: 'Single string.',
        outputFormat: 'Print reversed string.',
        sampleInput: 'hello',
        sampleOutput: 'olleh',
        explanation: 'StringBuilder has a reverse() method.',
        hint: 'new StringBuilder(s).reverse().toString()',
        answer: 'Scanner sc = new Scanner(System.in);\nString s = sc.next();\nSystem.out.println(new StringBuilder(s).reverse().toString());',
      ),
      ProblemData(
        title: 'HashMap Word Count',
        problem: 'Count word frequency in "the cat sat on the mat" using HashMap.',
        inputFormat: 'No input required.',
        outputFormat: 'Print each word and count.',
        sampleInput: '(none)',
        sampleOutput: 'the=2, cat=1, sat=1, on=1, mat=1',
        explanation: 'Split string, use HashMap getOrDefault to count.',
        hint: 'map.put(w, map.getOrDefault(w, 0) + 1)',
        answer: 'String sentence = "the cat sat on the mat";\nHashMap<String, Integer> map = new HashMap<>();\nfor (String w : sentence.split(" ")) {\n    map.put(w, map.getOrDefault(w, 0) + 1);\n}\nmap.forEach((k, v) -> System.out.println(k + "=" + v));',
      ),
    ],

    'Advanced Level': [
      ProblemData(
        title: 'Binary Search',
        problem: 'Implement binary search on sorted array {1,3,5,7,9,11,13}. Search for 9. Print index.',
        inputFormat: 'No input required.',
        outputFormat: 'Print index of 9.',
        sampleInput: '(none)',
        sampleOutput: '4',
        explanation: 'Divide search range in half each step. O(log n).',
        hint: 'int left=0, right=arr.length-1;\nwhile(left<=right) { int mid=(left+right)/2; }',
        answer: 'int[] arr = {1,3,5,7,9,11,13};\nint target = 9, left = 0, right = arr.length - 1;\nwhile (left <= right) {\n    int mid = (left + right) / 2;\n    if (arr[mid] == target) { System.out.println(mid); break; }\n    else if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n}',
      ),
      ProblemData(
        title: 'Stack using LinkedList',
        problem: 'Implement a Stack<Integer> using LinkedList. Push 1,2,3. Pop and print all.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 3\n2\n1',
        sampleInput: '(none)',
        sampleOutput: '3\n2\n1',
        explanation: 'LinkedList supports addFirst/removeFirst for stack (LIFO).',
        hint: 'LinkedList<Integer> stack = new LinkedList<>();\nstack.addFirst(x);\nstack.removeFirst();',
        answer: 'LinkedList<Integer> stack = new LinkedList<>();\nstack.addFirst(1);\nstack.addFirst(2);\nstack.addFirst(3);\nwhile (!stack.isEmpty()) {\n    System.out.println(stack.removeFirst());\n}',
      ),
      ProblemData(
        title: 'Generic Pair Class',
        problem: 'Create a generic class Pair<A, B> with two fields. Print Pair(1, "hello").',
        inputFormat: 'No input required.',
        outputFormat: 'Print: (1, hello)',
        sampleInput: '(none)',
        sampleOutput: '(1, hello)',
        explanation: 'Generics allow type-safe containers for different types.',
        hint: 'class Pair<A, B> {\n    A first;\n    B second;\n}',
        answer: 'class Pair<A, B> {\n    A first;\n    B second;\n    Pair(A a, B b) { first = a; second = b; }\n    public String toString() { return "(" + first + ", " + second + ")"; }\n}\nSystem.out.println(new Pair<>(1, "hello"));',
      ),
      ProblemData(
        title: 'Stream Filter & Map',
        problem: 'From list [1..10], use Java Streams to get even numbers multiplied by 2. Print result.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: [4, 8, 12, 16, 20]',
        sampleInput: '(none)',
        sampleOutput: '[4, 8, 12, 16, 20]',
        explanation: 'Use stream().filter().map().collect()',
        hint: 'IntStream.rangeClosed(1, 10)\n  .filter(n -> n % 2 == 0)\n  .map(n -> n * 2)',
        answer: 'List<Integer> result = IntStream.rangeClosed(1, 10)\n    .filter(n -> n % 2 == 0)\n    .map(n -> n * 2)\n    .boxed()\n    .collect(Collectors.toList());\nSystem.out.println(result);',
      ),
      ProblemData(
        title: 'Fibonacci Memoization',
        problem: 'Compute fib(10) using dynamic programming with a memo array.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 55',
        sampleInput: '(none)',
        sampleOutput: '55',
        explanation: 'Store previously computed Fibonacci values to avoid recalculation.',
        hint: 'int[] memo = new int[n+1];\nmemo[0]=0; memo[1]=1;',
        answer: 'int n = 10;\nint[] memo = new int[n + 1];\nmemo[0] = 0;\nmemo[1] = 1;\nfor (int i = 2; i <= n; i++) {\n    memo[i] = memo[i-1] + memo[i-2];\n}\nSystem.out.println(memo[n]);',
      ),
      ProblemData(
        title: 'Multithreading: Two Threads',
        problem: 'Create two threads. Thread 1 prints "Hello" 3 times. Thread 2 prints "World" 3 times.',
        inputFormat: 'No input required.',
        outputFormat: 'Hello and World printed 3 times each (order may vary).',
        sampleInput: '(none)',
        sampleOutput: 'Hello\nHello\nHello\nWorld\nWorld\nWorld',
        explanation: 'Implement Runnable or extend Thread. Call start().',
        hint: 'Thread t1 = new Thread(() -> { for(int i=0;i<3;i++) System.out.println("Hello"); });',
        answer: 'Thread t1 = new Thread(() -> {\n    for (int i = 0; i < 3; i++) System.out.println("Hello");\n});\nThread t2 = new Thread(() -> {\n    for (int i = 0; i < 3; i++) System.out.println("World");\n});\nt1.start();\nt2.start();',
      ),
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // C LANGUAGE
  // ══════════════════════════════════════════════════════════════════
  'C Language': {

    'Beginner Level': [
      ProblemData(
        title: 'Hello World',
        problem: 'Write a C program to print "Hello, World!".',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Hello, World!',
        sampleInput: '(none)',
        sampleOutput: 'Hello, World!',
        explanation: 'Include stdio.h and use printf() function.',
        hint: 'printf("Hello, World!\\n");',
        answer: '#include <stdio.h>\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Declare Variables',
        problem: 'Declare int age = 20 and float price = 9.99. Print both.',
        inputFormat: 'No input required.',
        outputFormat: 'Print age then price.',
        sampleInput: '(none)',
        sampleOutput: '20\n9.99',
        explanation: 'Use %d for int and %f for float in printf.',
        hint: 'printf("%d\\n", age);\nprintf("%.2f\\n", price);',
        answer: '#include <stdio.h>\nint main() {\n    int age = 20;\n    float price = 9.99;\n    printf("%d\\n", age);\n    printf("%.2f\\n", price);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Sum of Two Numbers',
        problem: 'Read two integers and print their sum.',
        inputFormat: 'Two integers on separate lines.',
        outputFormat: 'Print the sum.',
        sampleInput: '5\n3',
        sampleOutput: '8',
        explanation: 'Use scanf to read ints, add them, printf the result.',
        hint: 'scanf("%d %d", &a, &b);',
        answer: '#include <stdio.h>\nint main() {\n    int a, b;\n    scanf("%d %d", &a, &b);\n    printf("%d\\n", a + b);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Even or Odd',
        problem: 'Read an integer and print "Even" or "Odd".',
        inputFormat: 'Single integer.',
        outputFormat: 'Print Even or Odd.',
        sampleInput: '6',
        sampleOutput: 'Even',
        explanation: 'Check n % 2 == 0 for even.',
        hint: 'if (n % 2 == 0) printf("Even\\n");',
        answer: '#include <stdio.h>\nint main() {\n    int n;\n    scanf("%d", &n);\n    if (n % 2 == 0)\n        printf("Even\\n");\n    else\n        printf("Odd\\n");\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Print 1 to 5',
        problem: 'Use a for loop to print numbers 1 to 5.',
        inputFormat: 'No input required.',
        outputFormat: 'Print 1 through 5.',
        sampleInput: '(none)',
        sampleOutput: '1\n2\n3\n4\n5',
        explanation: 'for loop from i=1 to i<=5.',
        hint: 'for (int i = 1; i <= 5; i++)',
        answer: '#include <stdio.h>\nint main() {\n    for (int i = 1; i <= 5; i++) {\n        printf("%d\\n", i);\n    }\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Array Sum',
        problem: 'Declare int array {10,20,30,40,50} and print the sum.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 150',
        sampleInput: '(none)',
        sampleOutput: '150',
        explanation: 'Loop through array adding each element.',
        hint: 'int arr[] = {10,20,30,40,50};\nint sum = 0;',
        answer: '#include <stdio.h>\nint main() {\n    int arr[] = {10,20,30,40,50};\n    int sum = 0;\n    for (int i = 0; i < 5; i++) sum += arr[i];\n    printf("%d\\n", sum);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Function Add',
        problem: 'Write function int add(int a, int b) that returns a+b. Call with 4 and 6.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 10',
        sampleInput: '(none)',
        sampleOutput: '10',
        explanation: 'Declare function before main or use prototype.',
        hint: 'int add(int a, int b) { return a + b; }',
        answer: '#include <stdio.h>\nint add(int a, int b) {\n    return a + b;\n}\nint main() {\n    printf("%d\\n", add(4, 6));\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Factorial Loop',
        problem: 'Read n from user and print n! using a while loop.',
        inputFormat: 'Single integer n.',
        outputFormat: 'Print n factorial.',
        sampleInput: '5',
        sampleOutput: '120',
        explanation: 'Multiply i from 1 to n. Use while loop.',
        hint: 'int fact = 1, i = 1;\nwhile (i <= n) { fact *= i; i++; }',
        answer: '#include <stdio.h>\nint main() {\n    int n, fact = 1, i = 1;\n    scanf("%d", &n);\n    while (i <= n) {\n        fact *= i;\n        i++;\n    }\n    printf("%d\\n", fact);\n    return 0;\n}',
      ),
    ],

    'Intermediate Level': [
      ProblemData(
        title: 'Pointer Swap',
        problem: 'Write a function swap(int *a, int *b) that swaps two values using pointers.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: a=20 b=10',
        sampleInput: '(none)',
        sampleOutput: 'a=20 b=10',
        explanation: 'Dereference pointers to access and change values.',
        hint: 'void swap(int *a, int *b) {\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}',
        answer: '#include <stdio.h>\nvoid swap(int *a, int *b) {\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\nint main() {\n    int a = 10, b = 20;\n    swap(&a, &b);\n    printf("a=%d b=%d\\n", a, b);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'String Length',
        problem: 'Read a string and print its length WITHOUT using strlen().',
        inputFormat: 'Single word string.',
        outputFormat: 'Print the length.',
        sampleInput: 'hello',
        sampleOutput: '5',
        explanation: 'Traverse char array until \\0 null terminator.',
        hint: 'while (s[i] != \'\\0\') { len++; i++; }',
        answer: '#include <stdio.h>\nint main() {\n    char s[100];\n    scanf("%s", s);\n    int len = 0;\n    while (s[len] != \'\\0\') len++;\n    printf("%d\\n", len);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Structure: Student',
        problem: 'Define struct Student with name and grade. Create one student and print details.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Name: Alice, Grade: A',
        sampleInput: '(none)',
        sampleOutput: 'Name: Alice, Grade: A',
        explanation: 'struct groups related data. Access with dot operator.',
        hint: 'struct Student { char name[50]; char grade; };',
        answer: '#include <stdio.h>\nstruct Student {\n    char name[50];\n    char grade;\n};\nint main() {\n    struct Student s;\n    s.grade = \'A\';\n    sprintf(s.name, "Alice");\n    printf("Name: %s, Grade: %c\\n", s.name, s.grade);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Recursive Factorial',
        problem: 'Write recursive function int factorial(int n). Print factorial(6).',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 720',
        sampleInput: '(none)',
        sampleOutput: '720',
        explanation: 'Base: n==0 return 1. Recurse: n * factorial(n-1).',
        hint: 'int factorial(int n) {\n    if (n == 0) return 1;\n    return n * factorial(n - 1);\n}',
        answer: '#include <stdio.h>\nint factorial(int n) {\n    if (n == 0) return 1;\n    return n * factorial(n - 1);\n}\nint main() {\n    printf("%d\\n", factorial(6));\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Dynamic Array',
        problem: 'Allocate an int array of size 5 using malloc. Fill with 1-5. Print. Free memory.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 1 2 3 4 5',
        sampleInput: '(none)',
        sampleOutput: '1 2 3 4 5',
        explanation: 'malloc allocates heap memory. Always free() after use.',
        hint: 'int *arr = (int*)malloc(5 * sizeof(int));',
        answer: '#include <stdio.h>\n#include <stdlib.h>\nint main() {\n    int *arr = (int*)malloc(5 * sizeof(int));\n    for (int i = 0; i < 5; i++) arr[i] = i + 1;\n    for (int i = 0; i < 5; i++) printf("%d ", arr[i]);\n    free(arr);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Bubble Sort',
        problem: 'Sort array {64,25,12,22,11} using bubble sort. Print sorted.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 11 12 22 25 64',
        sampleInput: '(none)',
        sampleOutput: '11 12 22 25 64',
        explanation: 'Nested loops compare and swap adjacent elements.',
        hint: 'for(i=0;i<n-1;i++) for(j=0;j<n-i-1;j++) if(arr[j]>arr[j+1]) swap',
        answer: '#include <stdio.h>\nint main() {\n    int arr[] = {64,25,12,22,11};\n    int n = 5;\n    for (int i = 0; i < n-1; i++)\n        for (int j = 0; j < n-i-1; j++)\n            if (arr[j] > arr[j+1]) {\n                int tmp = arr[j];\n                arr[j] = arr[j+1];\n                arr[j+1] = tmp;\n            }\n    for (int i = 0; i < n; i++) printf("%d ", arr[i]);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'File Write & Read',
        problem: 'Write "Hello File" to a file "test.txt" then read and print its contents.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: Hello File',
        sampleInput: '(none)',
        sampleOutput: 'Hello File',
        explanation: 'Use fopen with "w" to write and "r" to read.',
        hint: 'FILE *f = fopen("test.txt", "w");\nfprintf(f, "Hello File");',
        answer: '#include <stdio.h>\nint main() {\n    FILE *f = fopen("test.txt", "w");\n    fprintf(f, "Hello File");\n    fclose(f);\n    f = fopen("test.txt", "r");\n    char buf[100];\n    fscanf(f, "%[^\\n]", buf);\n    printf("%s\\n", buf);\n    fclose(f);\n    return 0;\n}',
      ),
    ],

    'Advanced Level': [
      ProblemData(
        title: 'Linked List',
        problem: 'Implement singly linked list: create nodes 1->2->3 and print them.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 1 2 3',
        sampleInput: '(none)',
        sampleOutput: '1 2 3',
        explanation: 'Each node has data and next pointer. Traverse from head.',
        hint: 'struct Node { int data; struct Node *next; };',
        answer: '#include <stdio.h>\n#include <stdlib.h>\nstruct Node { int data; struct Node *next; };\nstruct Node* newNode(int d) {\n    struct Node *n = malloc(sizeof(struct Node));\n    n->data = d; n->next = NULL;\n    return n;\n}\nint main() {\n    struct Node *head = newNode(1);\n    head->next = newNode(2);\n    head->next->next = newNode(3);\n    struct Node *cur = head;\n    while (cur) { printf("%d ", cur->data); cur = cur->next; }\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Stack with Array',
        problem: 'Implement a stack using array with push, pop, peek. Push 1,2,3. Pop and print all.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 3\n2\n1',
        sampleInput: '(none)',
        sampleOutput: '3\n2\n1',
        explanation: 'Use top index. Push increments top, pop decrements.',
        hint: 'int stack[100], top = -1;\nvoid push(int x) { stack[++top] = x; }',
        answer: '#include <stdio.h>\nint stack[100], top = -1;\nvoid push(int x) { stack[++top] = x; }\nint pop() { return stack[top--]; }\nint main() {\n    push(1); push(2); push(3);\n    printf("%d\\n", pop());\n    printf("%d\\n", pop());\n    printf("%d\\n", pop());\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Binary Search',
        problem: 'Implement binary search on {1,3,5,7,9,11,13}. Find 9. Print index.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 4',
        sampleInput: '(none)',
        sampleOutput: '4',
        explanation: 'Divide and conquer. Mid check, adjust left or right.',
        hint: 'int left=0, right=n-1;\nwhile(left<=right) { int mid=(left+right)/2; }',
        answer: '#include <stdio.h>\nint main() {\n    int arr[] = {1,3,5,7,9,11,13};\n    int target = 9, left = 0, right = 6;\n    while (left <= right) {\n        int mid = (left + right) / 2;\n        if (arr[mid] == target) { printf("%d\\n", mid); return 0; }\n        else if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    printf("-1\\n");\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Bit Manipulation: Count Set Bits',
        problem: 'Count the number of set bits (1s) in the binary representation of 13.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 3 (13 = 1101 in binary)',
        sampleInput: '(none)',
        sampleOutput: '3',
        explanation: 'Use n & 1 to check last bit, right-shift n until 0.',
        hint: 'while (n) { count += n & 1; n >>= 1; }',
        answer: '#include <stdio.h>\nint main() {\n    int n = 13, count = 0;\n    while (n) {\n        count += n & 1;\n        n >>= 1;\n    }\n    printf("%d\\n", count);\n    return 0;\n}',
      ),
      ProblemData(
        title: 'Fibonacci DP Array',
        problem: 'Compute fib(10) using bottom-up dynamic programming array.',
        inputFormat: 'No input required.',
        outputFormat: 'Print: 55',
        sampleInput: '(none)',
        sampleOutput: '55',
        explanation: 'Fill dp[] from bottom up: dp[i] = dp[i-1] + dp[i-2].',
        hint: 'int dp[11];\ndp[0]=0; dp[1]=1;\nfor(int i=2;i<=10;i++) dp[i]=dp[i-1]+dp[i-2];',
        answer: '#include <stdio.h>\nint main() {\n    int dp[11];\n    dp[0] = 0; dp[1] = 1;\n    for (int i = 2; i <= 10; i++)\n        dp[i] = dp[i-1] + dp[i-2];\n    printf("%d\\n", dp[10]);\n    return 0;\n}',
      ),
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // HTML & CSS
  // ══════════════════════════════════════════════════════════════════
  'HTML & CSS': {

    'Beginner Level': [
      ProblemData(
        title: 'Basic HTML Page',
        problem: 'Write a complete HTML page with title "My Page" and an h1 heading "Hello World".',
        inputFormat: 'No input required.',
        outputFormat: 'Valid HTML with title and h1.',
        sampleInput: '(none)',
        sampleOutput: '<!DOCTYPE html>\n<html>\n<head><title>My Page</title></head>\n<body><h1>Hello World</h1></body>\n</html>',
        explanation: 'DOCTYPE, html, head, title, body, h1 are the basic structure.',
        hint: '<!DOCTYPE html>\n<html>\n<head><title>...</title></head>\n<body>...</body>\n</html>',
        answer: '<!DOCTYPE html>\n<html>\n<head><title>My Page</title></head>\n<body>\n  <h1>Hello World</h1>\n</body>\n</html>',
      ),
      ProblemData(
        title: 'Paragraph and Heading',
        problem: 'Write HTML with an h2 heading "About Me" and a paragraph "I love coding.".',
        inputFormat: 'No input required.',
        outputFormat: 'HTML with h2 and p tags.',
        sampleInput: '(none)',
        sampleOutput: '<h2>About Me</h2>\n<p>I love coding.</p>',
        explanation: 'h2 is a second-level heading. p is a paragraph.',
        hint: '<h2>text</h2>\n<p>text</p>',
        answer: '<h2>About Me</h2>\n<p>I love coding.</p>',
      ),
      ProblemData(
        title: 'Hyperlink',
        problem: 'Write HTML to create a link to https://google.com with text "Visit Google" opening in new tab.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML anchor tag.',
        sampleInput: '(none)',
        sampleOutput: '<a href="https://google.com" target="_blank">Visit Google</a>',
        explanation: 'target="_blank" opens link in new tab.',
        hint: '<a href="url" target="_blank">text</a>',
        answer: '<a href="https://google.com" target="_blank">Visit Google</a>',
      ),
      ProblemData(
        title: 'Unordered List',
        problem: 'Write HTML unordered list with 3 fruits: Apple, Banana, Cherry.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML ul with 3 li items.',
        sampleInput: '(none)',
        sampleOutput: '<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n  <li>Cherry</li>\n</ul>',
        explanation: 'ul creates bullet list, li for each item.',
        hint: '<ul>\n  <li>item</li>\n</ul>',
        answer: '<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n  <li>Cherry</li>\n</ul>',
      ),
      ProblemData(
        title: 'Simple Form',
        problem: 'Write HTML form with name text input, email input, and a submit button.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML form with inputs.',
        sampleInput: '(none)',
        sampleOutput: '<form>\n  <input type="text" placeholder="Name">\n  <input type="email" placeholder="Email">\n  <button type="submit">Submit</button>\n</form>',
        explanation: 'form wraps inputs. type attribute defines input type.',
        hint: '<form>\n  <input type="text">\n  <button type="submit">\n</form>',
        answer: '<form>\n  <input type="text" placeholder="Name">\n  <input type="email" placeholder="Email">\n  <button type="submit">Submit</button>\n</form>',
      ),
      ProblemData(
        title: 'CSS Text Style',
        problem: 'Write CSS to make h1 red, font-size 32px, and center aligned.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS rule for h1.',
        sampleInput: '(none)',
        sampleOutput: 'h1 {\n  color: red;\n  font-size: 32px;\n  text-align: center;\n}',
        explanation: 'CSS selector h1 applies styles to all h1 elements.',
        hint: 'h1 {\n  color: red;\n  font-size: 32px;\n}',
        answer: 'h1 {\n  color: red;\n  font-size: 32px;\n  text-align: center;\n}',
      ),
      ProblemData(
        title: 'Background Color',
        problem: 'Write CSS to set body background to #f0f0f0 and div background to lightblue.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS for body and div.',
        sampleInput: '(none)',
        sampleOutput: 'body {\n  background-color: #f0f0f0;\n}\ndiv {\n  background-color: lightblue;\n}',
        explanation: 'background-color sets element background.',
        hint: 'body { background-color: ...; }\ndiv { background-color: ...; }',
        answer: 'body {\n  background-color: #f0f0f0;\n}\ndiv {\n  background-color: lightblue;\n}',
      ),
      ProblemData(
        title: 'Box Model',
        problem: 'Write CSS for a div with: width 200px, padding 20px, border 2px solid black, margin 10px.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS div rule.',
        sampleInput: '(none)',
        sampleOutput: 'div {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n  margin: 10px;\n}',
        explanation: 'Box model: content + padding + border + margin.',
        hint: 'div { width: 200px; padding: 20px; border: 2px solid black; }',
        answer: 'div {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n  margin: 10px;\n}',
      ),
      ProblemData(
        title: 'Flexbox Center',
        problem: 'Write CSS to center items both horizontally and vertically inside a .container div.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS with flexbox centering.',
        sampleInput: '(none)',
        sampleOutput: '.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}',
        explanation: 'justify-content centers horizontally, align-items vertically.',
        hint: 'display: flex;\njustify-content: center;\nalign-items: center;',
        answer: '.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}',
      ),
      ProblemData(
        title: 'Media Query',
        problem: 'Write a media query so that when screen width is 600px or less, font-size becomes 14px.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS media query.',
        sampleInput: '(none)',
        sampleOutput: '@media (max-width: 600px) {\n  body {\n    font-size: 14px;\n  }\n}',
        explanation: '@media defines breakpoint. max-width 600px targets small screens.',
        hint: '@media (max-width: 600px) { body { font-size: 14px; } }',
        answer: '@media (max-width: 600px) {\n  body {\n    font-size: 14px;\n  }\n}',
      ),
    ],

    'Intermediate Level': [
      ProblemData(
        title: 'CSS Grid Layout',
        problem: 'Write CSS to create a 3-column grid layout with 20px gap.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS grid rule.',
        sampleInput: '(none)',
        sampleOutput: '.container {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 20px;\n}',
        explanation: '1fr = 1 fraction of available space. 3 equal columns.',
        hint: 'display: grid;\ngrid-template-columns: 1fr 1fr 1fr;',
        answer: '.container {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 20px;\n}',
      ),
      ProblemData(
        title: 'CSS Animation',
        problem: 'Write CSS to fade in a div from opacity 0 to 1 over 2 seconds.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS keyframes and animation property.',
        sampleInput: '(none)',
        sampleOutput: '@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}\ndiv {\n  animation: fadeIn 2s ease-in;\n}',
        explanation: '@keyframes defines the animation. animation applies it.',
        hint: '@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }',
        answer: '@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}\ndiv {\n  animation: fadeIn 2s ease-in;\n}',
      ),
      ProblemData(
        title: 'CSS Variables',
        problem: 'Define CSS variable --main-color as #3498db. Use it as text color for h1 and background for button.',
        inputFormat: 'No input required.',
        outputFormat: 'CSS with :root variable and usage.',
        sampleInput: '(none)',
        sampleOutput: ':root {\n  --main-color: #3498db;\n}\nh1 {\n  color: var(--main-color);\n}\nbutton {\n  background: var(--main-color);\n}',
        explanation: 'CSS variables declared in :root are global.',
        hint: ':root { --main-color: #3498db; }\nh1 { color: var(--main-color); }',
        answer: ':root {\n  --main-color: #3498db;\n}\nh1 {\n  color: var(--main-color);\n}\nbutton {\n  background: var(--main-color);\n}',
      ),
      ProblemData(
        title: 'Semantic HTML',
        problem: 'Write a semantic HTML page structure with header, nav, main, article, and footer.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML with semantic tags.',
        sampleInput: '(none)',
        sampleOutput: '<header>Header</header>\n<nav>Nav</nav>\n<main>\n  <article>Article</article>\n</main>\n<footer>Footer</footer>',
        explanation: 'Semantic tags describe meaning, improve SEO and accessibility.',
        hint: '<header>, <nav>, <main>, <article>, <footer>',
        answer: '<header>Header</header>\n<nav>Nav</nav>\n<main>\n  <article>Article content</article>\n</main>\n<footer>Footer</footer>',
      ),
      ProblemData(
        title: 'Responsive Nav Bar',
        problem: 'Write HTML+CSS for a nav bar that stacks vertically on screens below 600px.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML nav + CSS with media query.',
        sampleInput: '(none)',
        sampleOutput: '<nav class="navbar">\n  <a>Home</a>\n  <a>About</a>\n</nav>\n.navbar { display: flex; }\n@media(max-width:600px){.navbar{flex-direction:column;}}',
        explanation: 'Default flex row, media query switches to column on mobile.',
        hint: '.navbar { display: flex; }\n@media(max-width:600px) { .navbar { flex-direction: column; } }',
        answer: '<nav class="navbar">\n  <a href="#">Home</a>\n  <a href="#">About</a>\n</nav>\n<style>\n.navbar { display: flex; gap: 10px; }\n@media (max-width: 600px) {\n  .navbar { flex-direction: column; }\n}\n</style>',
      ),
      ProblemData(
        title: 'HTML Table',
        problem: 'Create an HTML table with headers Name and Age, and 2 rows of data.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML table.',
        sampleInput: '(none)',
        sampleOutput: '<table>\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>Alice</td><td>20</td></tr>\n  <tr><td>Bob</td><td>25</td></tr>\n</table>',
        explanation: 'tr = table row, th = header cell, td = data cell.',
        hint: '<table>\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>...</td><td>...</td></tr>\n</table>',
        answer: '<table border="1">\n  <tr><th>Name</th><th>Age</th></tr>\n  <tr><td>Alice</td><td>20</td></tr>\n  <tr><td>Bob</td><td>25</td></tr>\n</table>',
      ),
    ],

    'Advanced Level': [
      ProblemData(
        title: 'SCSS Mixin',
        problem: 'Write a SCSS mixin for flex-center that sets display:flex, justify-content:center, align-items:center. Use it on .box.',
        inputFormat: 'No input required.',
        outputFormat: 'SCSS with mixin definition and usage.',
        sampleInput: '(none)',
        sampleOutput: '@mixin flex-center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n.box {\n  @include flex-center;\n}',
        explanation: 'Mixins are reusable CSS blocks in SCSS.',
        hint: '@mixin name { ... }\n.class { @include name; }',
        answer: '@mixin flex-center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n.box {\n  @include flex-center;\n  width: 200px;\n  height: 200px;\n}',
      ),
      ProblemData(
        title: 'Accessible Form',
        problem: 'Write an accessible HTML form with label elements properly linked to inputs using for/id.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML form with labels.',
        sampleInput: '(none)',
        sampleOutput: '<form>\n  <label for="name">Name:</label>\n  <input id="name" type="text">\n  <label for="email">Email:</label>\n  <input id="email" type="email">\n</form>',
        explanation: 'for attribute in label matches id in input for accessibility.',
        hint: '<label for="name">Name:</label>\n<input id="name" type="text">',
        answer: '<form>\n  <label for="name">Name:</label>\n  <input id="name" type="text" required>\n  <label for="email">Email:</label>\n  <input id="email" type="email" required>\n  <button type="submit">Submit</button>\n</form>',
      ),
      ProblemData(
        title: 'SEO Meta Tags',
        problem: 'Write HTML head section with proper SEO meta tags: charset, viewport, description, and title.',
        inputFormat: 'No input required.',
        outputFormat: 'HTML head with meta tags.',
        sampleInput: '(none)',
        sampleOutput: '<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta name="description" content="Learn coding online">\n  <title>Smart Coder</title>\n</head>',
        explanation: 'Meta tags inform browsers and search engines about the page.',
        hint: '<meta charset="UTF-8">\n<meta name="viewport" ...>\n<meta name="description" ...>',
        answer: '<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta name="description" content="Learn coding online">\n  <title>Smart Coder</title>\n</head>',
      ),
    ],
  },
};
